name: Publish .NET package to NuGet

permissions:
  contents: read
  pull-requests: write
  
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies for src projects
        run: |
          for proj in $(find src -name '*.csproj'); do
            dotnet restore "$proj"
          done

      - name: Build src projects
        run: |
          for proj in $(find src -name '*.csproj'); do
            dotnet build "$proj" --configuration Release --no-restore
          done

      - name: Pack src projects
        run: |
          mkdir -p ./nupkg
          for proj in $(find src -name '*.csproj'); do
            dotnet pack "$proj" --configuration Release --no-build --output ./nupkg
          done      
          
      - name: Push the package to NuGet
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
